Add Author DTO and Implement POST Endpoint
333-Prod-Engineering/service pull request #1
Opened 2024-03-02 17:33 UTC by Qubicon

2024-03-03 10:00 UTC, irinaenescu2002 requested changes
Doua modificari mici

2024-03-03 10:00 UTC, irinaenescu2002 commented on src/main/java/ro/unibuc/hello/controller/AuthorController.java
> +        var newAuthor = authorService.saveAuthor(name, nationality);
Putem sa folosim direct ```var newAuthor = authorService.saveAuthor(authorCreationRequestDto.getName(), authorCreationRequestDto.getNationality());```, nu e necesar sa le salvam in variabile diferite.

2024-03-03 10:00 UTC, irinaenescu2002 commented on src/main/java/ro/unibuc/hello/service/AuthorService.java
> +    public AuthorEntity saveAuthor(String name, String nationality) {
Cred ca este o idee buna sa adaugam log-uri inca de pe acum, asa ca: 
1. Adauga adnotarea ```@Slf4j```
2. Adauga un log parametrizat de debug 
```log.debug("Creating a new author '{}' with nationality '{}'", name, nationality);```

2024-03-03 13:46 UTC, Qubicon commented
```
Reduce all commits to 1 on your feature branch before merging the PR (using rebase and squash).
```

So use **_Squash and merge_**.

2024-03-06 19:17 UTC, irinaenescu2002 approved these changes
Gj

2024-03-06 19:30 UTC, merged